language: python
os: linux
sudo: required
python:
  - "3.4"
  - "3.5"
  - "3.6"

virtualenv:
    system_site_package: true

before_install:
 - sudo apt-get update

install:
 - pip install -r requirements.txt

script:
  - sudo python3 -m unittest -v test_utility.py

notifications:
  email:
     on_success: change
     on_failure: always