language: python
os: linux
sudo: required
dist: trusty

python:
  - "3.4"
  - "3.5"
  - "3.6"

virtualenv:
    system_site_package: true

before_install:
 - sudo apt-get update > /dev/null
# - sudo apt upgrade > /dev/null

install:
 - pip install -r requirements.txt

script:
  - python3 -m unittest -v test.test_utility.py

notifications:
  email:
     on_success: never
     on_failure: always